<?php

namespace Cyberbrains\Filemanager;

use Illuminate\Contracts\Support\Arrayable;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
use JsonSerializable;

class FileResource extends JsonResource
{
    public function toArray($request): array|JsonSerializable|Arrayable
    {
        return [
            'link' => env('CDN_HOST') .'files/' .$this->link
        ]; // TODO: Change the autogenerated stub
    }
}